# Generated by Django 4.2 on 2024-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
